# 기본 설정
spring:
  config:
    activate:
      on-profile: dev # 기본 프로파일을 dev로 설정

---

# dev 프로파일
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/goods
    username: root
    password: namji
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        session:
          events:
            log: LOG_QUERIES_SLOWER_THAN_MS=3000
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      port: 6379
      host: localhost

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

admin:
  code: adbc7428nckamenwms

---
